/**
 * Published WS1300 firmware releases (public/firmware/ws1300/manifest.json),
 * generated by scripts/update-ws1300-manifest.mjs.
 */

import { compareHexHashes, sha256Hex } from '../flasher/hashing';
import { parseDfuPackage, type DfuImage } from './dfuPackage';

export const WS1300_MANIFEST_URL = '/firmware/ws1300/manifest.json';

export interface Ws1300ReleaseImage {
  file: string;
  image_index: number;
  core: 'app' | 'net';
  version: string;
  bytes: number;
  sha256: string;
}

export interface Ws1300Release {
  version: string;
  label: string;
  file: string;
  bytes: number;
  sha256: string;
  source_repo?: string;
  git_commit?: string;
  built_at?: string;
  images: Ws1300ReleaseImage[];
}

export interface Ws1300Manifest {
  schema: 1;
  hardware: 'WS1300';
  soc: string;
  latest: string;
  releases: Ws1300Release[];
}

const HEX64 = /^[0-9a-f]{64}$/i;

export function validateWs1300Manifest(raw: unknown): Ws1300Manifest {
  const m = raw as Partial<Ws1300Manifest> | null;
  if (!m || typeof m !== 'object') throw new Error('WS1300 manifest is not an object');
  if (m.schema !== 1) throw new Error(`Unsupported WS1300 manifest schema: ${String(m.schema)}`);
  if (m.hardware !== 'WS1300') throw new Error(`Manifest is for ${String(m.hardware)}, not WS1300`);
  if (!Array.isArray(m.releases) || m.releases.length === 0) throw new Error('WS1300 manifest lists no releases');

  for (const r of m.releases) {
    if (!r.version || !r.file || !r.file.startsWith('/firmware/ws1300/')) {
      throw new Error(`Release ${r.version ?? '?'} has an invalid file path`);
    }
    if (!HEX64.test(r.sha256)) throw new Error(`Release ${r.version} has an invalid sha256`);
    if (!Number.isInteger(r.bytes) || r.bytes <= 0) throw new Error(`Release ${r.version} has an invalid size`);
    if (!Array.isArray(r.images) || r.images.length === 0) throw new Error(`Release ${r.version} lists no images`);
    for (const img of r.images) {
      if (!HEX64.test(img.sha256)) throw new Error(`Release ${r.version} image ${img.file} has an invalid sha256`);
    }
  }
  if (!m.releases.some((r) => r.version === m.latest)) {
    throw new Error(`Manifest "latest" (${String(m.latest)}) is not in the release list`);
  }
  return m as Ws1300Manifest;
}

export async function loadWs1300Manifest(fetchImpl: typeof fetch = fetch): Promise<Ws1300Manifest> {
  const res = await fetchImpl(WS1300_MANIFEST_URL, { cache: 'no-cache' });
  if (!res.ok) throw new Error(`Could not load the WS1300 release list (HTTP ${res.status})`);
  return validateWs1300Manifest(await res.json());
}

export function latestRelease(m: Ws1300Manifest): Ws1300Release {
  return m.releases.find((r) => r.version === m.latest) ?? m.releases[0];
}

/** Download a release package, check it against the manifest and unpack it. */
export async function downloadRelease(
  release: Ws1300Release,
  fetchImpl: typeof fetch = fetch,
): Promise<DfuImage[]> {
  const res = await fetchImpl(release.file);
  if (!res.ok) throw new Error(`Could not download firmware ${release.label} (HTTP ${res.status})`);
  const bytes = new Uint8Array(await res.arrayBuffer());

  if (bytes.length !== release.bytes) {
    throw new Error(`Downloaded package is ${bytes.length} bytes, expected ${release.bytes}. Reload the page and try again.`);
  }
  const sha = await sha256Hex(bytes);
  if (!compareHexHashes(sha, release.sha256)) {
    throw new Error('Downloaded package failed its checksum. Reload the page and try again.');
  }

  const images = await parseDfuPackage(bytes, release.file.split('/').pop());
  for (const expected of release.images) {
    const got = images.find((i) => i.imageIndex === expected.image_index);
    if (!got || !compareHexHashes(got.sha256, expected.sha256)) {
      throw new Error(`Image ${expected.file} in the package does not match the release manifest`);
    }
  }
  return images;
}

/** Compare dotted numeric versions ("22.4.0" vs "22.3.0.1"). */
export function compareVersions(a: string, b: string): number {
  const pa = a.split(/[.+]/).map((x) => Number.parseInt(x, 10) || 0);
  const pb = b.split(/[.+]/).map((x) => Number.parseInt(x, 10) || 0);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] ?? 0) - (pb[i] ?? 0);
    if (d !== 0) return d < 0 ? -1 : 1;
  }
  return 0;
}
